### ISSUE TITLE
[Payment] WitnessScriptHash

### ISSUE THREAD

**Issue by altafan** [vulpemventures/go-elements#12]
A `WitnessScriptHash` method similar to the `WitnessPubKeyHash` one must be added to the `*Payment` type in order to return a bech32 encoded p2wsh address string, generated from either Hash or from Redeem (in order of least effort).

Ref: #8.

**Comment by sekulicd** [comment]
@altafan please advise if bellow test case corresponds to task requirement:
```
p2wpkh := payment.FromPublicKey(publicKey,Regtest)
redeem := payment.FromPayment(p2wpkh,Regtest)
p2wsh := redeem.WitnessScriptHash()
```

If this is the case we would have two methods which are returning valid values only if FromPayment factory method is called before their invocation:
```
ScriptHash()
WitnessScriptHash()
```
, if this is true, would it be better if those two methods have Payment as an input param? 
, so that we don't allow a user of the package to do below:
```
p2pkh/p2wpkh := payment.FromPublicKey
p2sh/p2wsh := payment.ScriptHash()/payment.WitnessScriptHash()
```
which would return wrong values.

**Comment by altafan** [comment]
Yes,  the example is correct. Thanks for pointing this out. 

Instead of passing the payment as an argument to the `ScriptHash` and `WitnessScriptHash` functions, we force them on working only with "nested payments".
In our implementation, nested payments are those payments that have a non-nil `Redeem` field.

The factory methods `FromPayment` and `FromScript` are intended to return nested payment.
I'm going to add a comment to #10 to better explain how to accomplish this goal.

**Comment by altafan** [comment]
We should definitely add a checkpoint to actually be sure that `Redeem` and `Redeem.Script` are not `nil` into `ScriptHash` and `WitnessScriptHash` methods.  This would prevent unexpected behaviors when calling these functions.
