### ISSUE TITLE
[unconfidential] Issue an asset

### ISSUE THREAD

**Issue by tiero** [vulpemventures/go-elements#26]
An user should be able to make a raw issuance unblinded defining initial supply, re-issuance tokens and so on

**Comment by altafan** [comment]
In order to support asset issuances we need to create 3 methods in our `transaction` package:

* `GenerateAssetEntropy` that creates the entropy for the generation of the asset id starting from:
   * an output represented by a transaction hash and an output index
    * a contract as the Ricardian asset contract in the form
    ```
    {
        "name": "test",
        "ticker": "TST",
        "entity": { "domain": "test.io" },
        "version": 0,
        "precision": 0
    }
    ``` 
* `GenerateAssetHash` that creates the asset hash starting from an entropy
* `GenerateReissuanceToken` that creates the reissuance token from an entropy

**Comment by altafan** [comment]
The steps to manually create a transaction with an issuance of a new asset are:
1. Add inputs to cover network fees. The first input that has an empty issuance will be used for issuing the asset. So typically the input `0` is used but in case of a transaction with 2 issuances, for the second will be used the input `1`, thus there must be at least one input per issuance in the transaction.
2. Add one output with the provided asset amount (in case if non-zero of course) and "owner" address. At this moment the asset hash has not been created yet, thus we will use the `0x00...01` 33-byte array. 
3. Add one output with the provided token amount (in case if non-zero of course) and "owner" address. We will use the `0x00...02` 33-byte array as the asset hash.
4. Add change output if needed.
5. Generate the asset entropy, hash and reissuance token.
6. Assign generated asset hash and reissuance token to the issuance input.

In order to abstract all these steps to the user of this library, we could add a `AddIssuance` function to the `*Transaction` type that expects just a issuance amount and a token amount and performs all the steps above, by returning just the asset hash and reissuance token.

**Comment by altafan** [comment]
In the same way we could then also provide the `AddReissuance` method so we keep the 2 options separated.
I think this way the usage would be more clear.

**Comment by tiero** [comment]
These methods would not be modifying the `Transaction` as addInput and addOuput do? It's just a pure function without side effect isn't?

**Comment by altafan** [comment]
These methods do modify the `Transaction` as those you mentioned.
They modify the `Outputs` by adding the outputs for the issuance amount and/or the reissuance token amount.
The `AddIssuance` method also modifies the `Inputs` by adding the `Issuance` to the first available input.

**Comment by tiero** [comment]
Ok, I may have misinterpreted your previous comment. This makes sense. The returned values (assetHash, reissuanceToken) are then returned for convenience? As you point out they could still be read from the Transaction itself just in case.

**Comment by altafan** [comment]
> The returned values (assetHash, reissuanceToken) are then returned for convenience?
Yes, but I guess the user would be happy to not be forced to iterate over the transaction outputs to know the hash of its minted asset and/or reissuance token

**Comment by tiero** [comment]
Go ahead and split the tickets please
