### ISSUE TITLE
[Story] Add Secp256k1-zkp support

### ISSUE THREAD

**Issue by tiero** [vulpemventures/go-elements#42]
Add zkp support to the library. Using an already developed go library would be ok to start. Eg. [https://github.com/olegabu/go-secp256k1-zkp ](https://github.com/olegabu/go-secp256k1-zkp )

**Comment by altafan** [comment]
I tried to import the lib in a new project and it seems to work as expected.
This is my simple `main.go` so far:
```
package main

import (
	"crypto/rand"
	"fmt"
	"os"
	"unsafe"

	"github.com/olegabu/go-secp256k1-zkp"
)

func exit(err interface{}) {
	fmt.Println(err)
	os.Exit(1)
}

func main() {
	ctxNone, _ := secp256k1.ContextCreate(secp256k1.ContextNone)
	defer secp256k1.ContextDestroy(ctxNone)

	var valuebytes [8]byte
	valueLen, err := rand.Read(valuebytes[:])
	if err != nil {
		exit(err)
	}
	value := *(*uint64)(unsafe.Pointer(&valuebytes[0]))
	fmt.Printf("value=%v, valueLen=%v\n", value, valueLen)

	var blind [32]byte
	blindLen, err := rand.Read(blind[:])
	if err != nil {
		exit(err)
	}
	fmt.Printf("blind=%v, blindLen=%v\n", blind, blindLen)

	comNone, err := secp256k1.Commit(ctxNone, blind[:], value, &secp256k1.GeneratorH, &secp256k1.GeneratorG)
	if err != nil {
		exit(err)
	}
	fmt.Printf("comNone=%v\n", comNone)
}
```

It correctly prints a random value, a blinding factor and pedersen commitment, so this means that this lib is usable, a little at least.

My next step will be to try to test all fixtures of our tests for the secp256k1-zkp lib for js in order to check that these go functions actually return the expected values (those fixtures are taken from the native C version).

**IMPORTANT**
I already noticed that there is no wrapper for the methods of the native `rangeproof` module and this is something that we must provide.

**Comment by tiero** [comment]
Thanks @altafan 

Yeah I think it's worth to use it for the time being to jump start the support and making a wrapper for only the rangeproof it's not a big deal and we could contribute to them.

**Comment by altafan** [comment]
Yeah that could definitely be a solution. 

One thing I forgot to tell in the previous comment is that using the library produces an annoying warning in the terminal:
```
In file included from $GOPATH/pkg/mod/github.com/olegabu/go-secp256k1-zkp@v0.2.8/secp256k1.go:21:
In file included from $GOPATH/pkg/mod/github.com/olegabu/go-secp256k1-zkp@v0.2.8/./secp256k1-zkp/src/secp256k1.c:709:
$GOPATH/pkg/mod/github.com/olegabu/go-secp256k1-zkp@v0.2.8/secp256k1-zkp/src/modules/surjection/main_impl.h:211:9: warning: comparison of nonnull parameter 'proof' not equal to a null pointer is 'true' on first encounter [-Wtautological-pointer-compare]
$GOPATH/pkg/mod/github.com/olegabu/go-secp256k1-zkp@v0.2.8/secp256k1-zkp/include/secp256k1_surjectionproof.h:219:3: note: declared 'nonnull' here
$GOPATH/pkg/mod/github.com/olegabu/go-secp256k1-zkp@v0.2.8/secp256k1-zkp/include/secp256k1.h:152:54: note: expanded from macro 'SECP256K1_ARG_NONNULL'
```

**Comment by altafan** [comment]
By investing more in deep, I found that this CGO porting is based on the mimblewimble C implementation of secp256k1-zkp, that, of course is similar, but has some difference compared to the elements one 😞.

One little but substantial difference, for example, is in the `secp256k1_perdersen_commit` function, that in the mimblewimble version expects 6 arguments while in elements it expects 5. It seems to me that a the one missing in elements is automatically calculated/derived from the context, but it's hard to say now. And I did not finish checking all the native methods yet.

It may be better to write our own porting and import all the reusable code?

**Comment by tiero** [comment]
I think we should investigate with same test vectors of elements zkp and see if the functions we need pass those.

**Comment by altafan** [comment]
Consider that some of the test vectors of the elements zkp are not suitable for the function of the mimblewimble version since the implementations are slightly different.

As I said before, even if the same methods of these 2 libs eventually return the same results, they may differ in the number of arguments expected, so this would mean studying another implementation to understand how to correctly use them and provided new test cases.
And still, we would need to implement bindings for the `secp256k1_rangeproof` module.


I think that this effort would be bigger than just reuse the bindings from https://github.com/olegabu/go-secp256k1-zkp and adapt them to work with the elements zkp lib:
* we already have confidence with this implementation
* we have test vectors that we can trust
