### ISSUE TITLE
[Payment] Support for base58 confidential addresses

### ISSUE THREAD

**Issue by tiero** [vulpemventures/go-elements#83]
At the moment we do not support the blinding key when creating a legacy base58 address. We need to add the blinding key when encoding and extract it when decoding

**Comment by altafan** [comment]
The `Payment` type already has a `BlindingKey` field that is intended to use for supporting confidential addresses.

We should change the implementation of the `FromPublicKey`, `FromPublicKeys` and the `FromScript` functions so that they all expect one more argument `blindingKey` of type `*btcec.PublicKey`. If the passed blinding key is not nil, then it is set for the returned `*Payment`.

We should also change the `PubKeyHash` and `ScriptHash` functions so that they return a confidential address by default when the payment's `BlindingKey` is not nil.

The confidential address version is basically the base58 encoding of the raw bytes:
```
CONFIDENTIAL_PREFIX | ADDRESS_PREFIX | BLINDING_PUBKEY | PK/SCRIPT_HASH
```

[This](https://github.com/vulpemventures/liquidjs-lib/blob/97673986c4233dee61f98dc59b5256ed2a8f313d/ts_src/address.ts#L253) shows how to create a conf address from a unconfidential legacy one.

Note: the confidential prefix can be taken directly from the `Network` field of the payment.
